In [49]:
import cv2
import numpy as np

In [3]:
# Q1: Channel swap

img = cv2.imread('imori.jpg')

# use the numpy list slice inverse
img[:,:,:] = img[:,:,::-1]  

# cv2.imwrite("out.jpg", img)
cv2.imshow("result", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [66]:
# Q2: Grayscale

# Y = 0.2126 R + 0.7152 G + 0.0722 B

img = cv2.imread('imori.jpg')

# --------------------------------------------------------
b = img[:,:,0] * 0.0722
g = img[:,:,1] * 0.7152
r = img[:,:,2] * 0.2126

res = (b + g + r).astype(np.uint8)

# cv2.imwrite("res.jpg", res)
cv2.imshow("result", res)
cv2.waitKey(0)
cv2.destroyAllWindows()

#----------------------------------------------------------
# numpy dot multiply:

res1 = np.dot(img[:,:,:],np.array([0.0722,0.7152,0.2126])).astype(np.uint8)

# cv2.imwrite("res1.jpg", res1)
cv2.imshow("result1", res1)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [71]:
# Q3: Thresholding

img = cv2.imread('imori.jpg')

# Grayscalize
temp = np.dot(img[:,:,:],np.array([0.0722,0.7152,0.2126])).astype(np.uint8)
# if < 128: 0 else 255
res = np.where(temp<128,0,255).astype(np.uint8)

# cv2.imwrite("res.jpg", res)
cv2.imshow("result", res)
cv2.waitKey(0)
cv2.destroyAllWindows()

# or 
# temp[temp<128] = 0
# temp[temp>=128] = 255

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ... 255 255   0]
 [  0   0   0 ... 255 255   0]
 ...
 [255   0   0 ...   0   0   0]
 [255   0   0 ...   0   0   0]
 [255 255   0 ...   0   0   0]]


In [ ]:
# Q4: Otsu's Method

